PRENATALv2/Areas/Records/Controllers/PregnanciesPreviousController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PRENATALv2.Areas.Home.Data;
using PRENATALv2.Areas.Home.Models;
using PRENATALv2.Areas.Records.Models;

namespace PRENATALv2.Areas.Records.Controllers
{
    [Area("Records")]
    [Authorize(Roles = "Patient, Doctor, Nurse")]
    [AutoValidateAntiforgeryToken]
    public class PregnanciesPreviousController : Controller
    {
        private Context _db { get; }
        public PregnanciesPreviousController(Context context)
        {
            _db = context;
        }
        public IActionResult Show(int Id)
        {
            PregnanciesPreviousMR x = new PregnanciesPreviousMR();
            x.MedicalRecordId = Id;
            x.Pregnancies = _db.PreviousPregnancyHistory.Where(a => a.MedicalRecordId == Id).Select(x => new PregnanciesPreviousMR.Details
            {
                Id = x.PreviousPregnancyHistoryId,
                PregnancyDate = x.PregnancyDate,
                GestationWeeks=x.GestationWeeks,
                DeliveryType = x.DeliveryType,
                Complications=x.Complications,
                Outcome=x.Outcome
            }).ToList();

            return PartialView("_Show", x);
        }
        [Authorize(Roles = "Doctor, Nurse")]
        public IActionResult Add(int Id)
        {
            PregnanciesPreviousMR.Details x = new PregnanciesPreviousMR.Details();
            x.MedicalRecordId = Id;
            x.Outcomes= new List<SelectListItem>{
                new SelectListItem() { Value="Baby Boy", Text="Baby Boy"},
                new SelectListItem() { Value = "Baby Girl", Text = "Baby Girl" }
            };
            return PartialView("_Add", x);
        }
        [Authorize(Roles = "Doctor, Nurse")]
        public IActionResult Save(PregnanciesPreviousMR.Details input)
        {

            PreviousPregnancyHistory x = new PreviousPregnancyHistory();
            x.PregnancyDate = input.PregnancyDate;
            x.GestationWeeks = input.GestationWeeks;
            x.DeliveryType = input.DeliveryType;
            x.Complications = input.Complications;
            x.Outcome = input.Outcome;
            x.MedicalRecordId = input.MedicalRecordId;
            _db.PreviousPregnancyHistory.Add(x);
            _db.SaveChanges();
            _db.Dispose();
            return Redirect("/Records/MedicalRecords/ShowOne?Id=" + x.MedicalRecordId);
        }
        [Authorize(Roles = "Doctor, Nurse")]
        public IActionResult Edit(int Id)
        {
            PregnanciesPreviousMR.Details x = new PregnanciesPreviousMR.Details();
            PreviousPregnancyHistory y = _db.PreviousPregnancyHistory.Where(i => i.PreviousPregnancyHistoryId == Id).SingleOrDefault();

            x.Id = y.PreviousPregnancyHistoryId;
            x.MedicalRecordId = y.MedicalRecordId;
            x.PregnancyDate = y.PregnancyDate;
            x.GestationWeeks = y.GestationWeeks;
            x.DeliveryType = y.DeliveryType;
            x.Complications = y.Complications;
            x.Outcome = y.Outcome;
            x.Outcomes = new List<SelectListItem>{
                new SelectListItem() { Value="Baby Boy", Text="Baby Boy"},
                new SelectListItem() { Value = "Baby Girl", Text = "Baby Girl" }
            };
            return PartialView("_Edit", x);
        }
        [Authorize(Roles = "Doctor, Nurse")]
        public IActionResult SaveExisting(PregnanciesPreviousMR.Details input)
        {
            PreviousPregnancyHistory x = _db.PreviousPregnancyHistory.Where(i => i.PreviousPregnancyHistoryId == input.Id).SingleOrDefault();
            x.PreviousPregnancyHistoryId = input.Id;
            x.PregnancyDate = input.PregnancyDate;
            x.GestationWeeks = input.GestationWeeks;
            x.DeliveryType = input.DeliveryType;
            x.Outcome = input.Outcome;
            x.Complications = input.Complications;
            x.MedicalRecordId = input.MedicalRecordId;

            _db.PreviousPregnancyHistory.Update(x);
            _db.SaveChanges();
            _db.Dispose();
            return Redirect("/Records/MedicalRecords/ShowOne?Id=" + input.MedicalRecordId);
        }
        [Authorize(Roles = "Doctor, Nurse")]
        public IActionResult Delete(int Id)
        {
            PreviousPregnancyHistory x = _db.PreviousPregnancyHistory.Where(i => i.PreviousPregnancyHistoryId == Id).SingleOrDefault();
            _db.PreviousPregnancyHistory.Remove(x);
            _db.SaveChanges();
            _db.Dispose();
            return Redirect("/Records/MedicalRecords/ShowOne?Id=" + x.MedicalRecordId);
        }
    }
}

PRENATALv2/Areas/Records/Views/PregnanciesPrevious/_Add.cshtml
@using PRENATALv2.Areas.Records.Models
@model PregnanciesPreviousMR.Details

    <div class="container border-bottom">

        <h3><strong class="text-uppercase">Add previous pregnancy:</strong></h3>
        @using (Html.BeginForm("Save", "PregnanciesPrevious", FormMethod.Post, new { @class = "form-group" }))
        {
            @Html.AntiForgeryToken();
            <fieldset class="align-content-lg-around">
                @Html.HiddenFor(Model => Model.MedicalRecordId, new { @class = "d-none" })
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.PregnancyDate, new { @class = "col-sm-12" })<br />
                    @Html.TextBoxFor(Model => Model.PregnancyDate, new { @type = "date", @class = "datepicker form-control" })<br />
                    @Html.ValidationMessageFor(Model => Model.PregnancyDate, "", new { @class = "text-danger" })
                </div>
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.GestationWeeks, new { @class = "col-sm-12" })<br />
                    @Html.TextBoxFor(Model => Model.GestationWeeks, new { @class = "form-control" })<br />
                    @Html.ValidationMessageFor(Model => Model.GestationWeeks, "", new { @class = "text-danger" })
                </div>
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.DeliveryType, new { @class = "col-sm-12" })<br />
                    @Html.TextBoxFor(Model => Model.DeliveryType, new { @class = "form-control" })<br />
                    @Html.ValidationMessageFor(Model => Model.DeliveryType, "", new { @class = "text-danger" })
                </div>
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.Complications, new { @class = "col-sm-12" })<br />
                    @Html.TextBoxFor(Model => Model.Complications, new { @class = "form-control" })<br />
                    @Html.ValidationMessageFor(Model => Model.Complications, "", new { @class = "text-danger" })
                </div>
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.Outcome, new { @class = "col-sm-12" })<br />
                    @Html.DropDownListFor(Model => Model.Outcome, new SelectList(Model.Outcomes, "Value", "Text"), "Select:", new { @class = "form-control" })<br />
                    @Html.ValidationMessageFor(Model => Model.Outcome, "", new { @class = "text-danger" })
                </div>
                <div class="d-inline">
                    <button id="add_cancel" class="btn btn-small form-control">Cancel</button>
                    <input type="submit" class="btn btn-small form-control" value="Save" />
                </div>

            </fieldset>
        }

    </div>
<script>
    $('#add_cancel').click(function () {

        $(this).parent().parent().parent().parent().parent().empty();
    });
</script>

PRENATALv2/Areas/Records/Views/PregnanciesPrevious/_Edit.cshtml
@using PRENATALv2.Areas.Records.Models
@model PregnanciesPreviousMR.Details

    <div class="container border-bottom">
        <h3><strong class="text-uppercase">Edit previous pregnancy</strong></h3>
        @using (Html.BeginForm("SaveExisting", "PregnanciesPrevious", FormMethod.Post, new { @class = "form-group" }))
        {

            @Html.AntiForgeryToken();
            <fieldset class="align-content-lg-around">

                @Html.HiddenFor(Model => Model.MedicalRecordId, new { @class = "d-none" })
                @Html.HiddenFor(Model => Model.Id, new { @class = "d-none" })
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.PregnancyDate, new { @class = "col-sm-12" })<br />
                    @Html.EditorFor(Model => Model.PregnancyDate, new { htmlAttributes = new { @type = "date", @class = "datepicker form-control" } })<br />
                    @Html.ValidationMessageFor(Model => Model.PregnancyDate, "", new { @class = "text-danger" })
                </div>
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.GestationWeeks, new { @class = "col-sm-12" })<br />
                    @Html.EditorFor(Model => Model.GestationWeeks, new { htmlAttributes = new { @class = "form-control" } })<br />
                    @Html.ValidationMessageFor(Model => Model.GestationWeeks, "", new { @class = "text-danger" })
                </div>
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.DeliveryType, new { @class = "col-sm-12" })<br />
                    @Html.EditorFor(Model => Model.DeliveryType, new { htmlAttributes = new { @class = "form-control" } })<br />
                    @Html.ValidationMessageFor(Model => Model.DeliveryType, "", new { @class = "text-danger" })
                </div>
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.Complications, new { @class = "col-sm-12" })<br />
                    @Html.EditorFor(Model => Model.Complications, new { htmlAttributes = new { @class = "form-control" } })<br />
                    @Html.ValidationMessageFor(Model => Model.Complications, "", new { @class = "text-danger" })
                </div>
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.Outcome, new { @class = "col-sm-12" })<br />
                    @Html.DropDownListFor(Model => Model.Outcome, new SelectList(Model.Outcomes, "Value", "Text", Model.Outcome), "Select:", new { @class = "form-control" })<br />
                    @Html.ValidationMessageFor(Model => Model.Outcome, "", new { @class = "text-danger" })
                </div>

                <div class="d-inline">
                    <button id="edit_cancel" class="btn btn-small form-control">Cancel</button>
                    <input type="submit" class="btn btn-small form-control" value="Save" />
                </div>
            </fieldset>
        }
    </div>
<script>
    $('#edit_cancel').click(function () {
        $(this).parent().parent().parent().parent().parent().empty();
    });
</script>

PRENATALv2/Areas/Records/Views/PregnanciesPrevious/_Show.cshtml
@using PRENATALv2.Areas.Records.Models;
@model PregnanciesPreviousMR
@Html.AntiForgeryToken()
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" />
<div class="container">
    <div class="text-left" style="vertical-align:middle;">
        @{ if (User.IsInRole("Nurse") || User.IsInRole("Doctor"))
            {
                <button style="vertical-align:middle; font-size:20px;" id="_pregnancyprevious_add" class="btn fas fa-plus-square d-inline"></button>
            }
        }

        <h5 style="vertical-align:middle;" class="d-inline"><strong class="text-uppercase">Prev.Pregnancies:</strong></h5>
    </div>

    @{
        if (Model.Pregnancies.Count > 0)
        {

            <div class="container">


                <div class="row row_head">
                    <div class="col" hidden>Id</div>
                    <div class="col">Date</div>
                    <div class="col">GestationWeeks</div>
                    <div class="col">DeliveryType</div>
                    <div class="col">Complications</div>
                    <div class="col">Outcome</div>
                    <div class="col"></div>
                    <div class="col"></div>
                    <div class="col"></div>
                    <div class="col"></div>
                    <div class="col"></div>

                    <div class="col">Actions</div>
                </div>



                @foreach (PregnanciesPreviousMR.Details x in Model.Pregnancies)
                {

                    <div class="row row_data">
                        <div class="col" hidden>@x.Id</div>
                        <div class="col">@x.PregnancyDate.ToShortDateString()</div>
                        <div class="col">@x.GestationWeeks</div>
                        <div class="col">@x.DeliveryType</div>
                        <div class="col">@x.Complications</div>
                        <div class="col">@x.Outcome</div>
                        <div class="col"></div>
                        <div class="col"></div>
                        <div class="col"></div>
                        <div class="col"></div>
                        <div class="col"></div>

                        <div class="col">
                            @{ if (User.IsInRole("Nurse") || User.IsInRole("Doctor"))
                                {
                                    <i style="font-size:20px;" class="_pregnancyprevious_edit fas fa-edit a_icon"></i>
                                    <a style="font-size:20px;" class="_pregnancyprevious_delete fas fa-trash-alt a_icon" href="/Records/PregnanciesPrevious/Delete?Id=@x.Id"></a>
                                }
                                else
                                { <div>N/A</div>}
                            }

                        </div>
                    </div>


                }

            </div>

        }

    }
    <div class="container" id="_pregnanciesprevious_add"></div>
    <div class="container" id="_pregnanciesprevious_edit"></div>
</div>


<script>
        $('._pregnancyprevious_edit').click(function () {
            if ($('#_pregnanciesprevious_edit').html() == "") {
            var i = $(this).parent().parent().children().html();
            $.ajax({
                url: "/Records/PregnanciesPrevious/Edit?Id=" + i,
                type: "GET",
                dataType: "html",
                success: function (data) {
                    $("#_pregnanciesprevious_edit").html(data);
                },
                complete: function () {
                    $("form").each(function () { $.data($(this)[0], 'validator', false); });
                    $.validator.unobtrusive.parse("form");
                }
            });
        } else {
                $('#_pregnanciesprevious_edit').empty();
        }

    });
        $('#_pregnancyprevious_add').click(function () {
        if ($('#_pregnanciesprevious_add').html() == "") {

            $.ajax({
                url: "/Records/PregnanciesPrevious/Add?Id="+@Model.MedicalRecordId,
                type: "GET",
                dataType: "html",
                success: function (data) {

                    $("#_pregnanciesprevious_add").html(data);

                },
                complete: function () {
                    $("form").each(function () { $.data($(this)[0], 'validator', false); });
                    $.validator.unobtrusive.parse("form");

                }
            });
        } else {
            $('#_pregnanciesprevious_add').empty();
        }
    });
</script>