PRENATALv2/Areas/Records/Models/Partners.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PRENATALv2.Areas.Records.Models
{
    public class Partners
    {
        public int MedicalRecordId { get; set; }
        public List<Details> ListPartners { get; set; }

        public class Details
        {
            public int PartnerId { get; set; }

            [StringLength(15, ErrorMessage = "Length must be between 2 and 15 characters", MinimumLength = 2)]
            [Required(ErrorMessage = "This field is required!")]
            public string Name { get; set; }

            [StringLength(30, ErrorMessage = "Length must be between 2 and 15 characters", MinimumLength = 2)]
            [Required(ErrorMessage = "This field is required!")]
            public string Surname { get; set; }

            [MaxLength(2, ErrorMessage = "MaxLength 2 characters")]
            [Required(ErrorMessage = "This field is required!")]
            public string BloodType { get; set; }

            [MaxLength(1, ErrorMessage = "MaxLength 1 characters")]
            [Required(ErrorMessage = "This field is required!")]
            public string RHFactor { get; set; }

            public List<SelectListItem> BloodTypes { get; set; }
            public List<SelectListItem> RhFactors { get; set; }
            public int MedicalRecordId { get; set; }
        }
    }
}

PRENATALv2/Areas/Records/Controllers/PartnersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PRENATALv2.Areas.Home.Data;
using PRENATALv2.Areas.Home.Models;
using PRENATALv2.Areas.Records.Models;

namespace PRENATALv2.Areas.Records.Controllers
{
    [Area("Records")]
    [Authorize(Roles ="Patient, Doctor, Nurse")]
    [AutoValidateAntiforgeryToken]
    public class PartnersController : Controller
    {
        private Context _db { get; }
        public PartnersController(Context context)
        {
            _db = context;
        }
        public IActionResult Show(int Id)
        {
            Partners x = new Partners();
            x.MedicalRecordId = Id;
            x.ListPartners= _db.Partner.Where(a => a.MedicalRecordId == Id).Select(x=>new Partners.Details
            {
                PartnerId=x.PartnerId,
                Name=x.Name,
                Surname=x.Surname,
                BloodType=x.BloodType,
                RHFactor=x.RHFactor
            }).ToList();

            return PartialView("_Show",x);
        }
        [Authorize(Roles = "Doctor, Nurse")]
        public IActionResult Add(int Id)
        {
            Partners.Details x = new Partners.Details();
            x.MedicalRecordId = Id;
            x.BloodTypes = new List<SelectListItem>
            {
                new SelectListItem(){Value="A", Text="A"},
                new SelectListItem(){Value="B", Text="B"},
                new SelectListItem(){Value="0", Text="0"},
                new SelectListItem(){Value="AB", Text="AB"}
            };
            x.RhFactors = new List<SelectListItem>
            {
                new SelectListItem(){Value="+", Text="+"},
                new SelectListItem(){Value="-", Text="-"}
                
            };
            return PartialView("_Add", x);
        }
        [Authorize(Roles = "Doctor, Nurse")]
        public IActionResult Save(Partners.Details input)
        {

            Partner x = new Partner();
            x.Name = input.Name;
            x.Surname = input.Surname;
            x.BloodType = input.BloodType;
            x.RHFactor = input.RHFactor;
            x.MedicalRecordId = input.MedicalRecordId;
            _db.Partner.Add(x);
            _db.SaveChanges();
            _db.Dispose();
            return Redirect("/Records/MedicalRecords/ShowOne?Id=" + x.MedicalRecordId);
        }
        [Authorize(Roles = "Doctor, Nurse")]
        public IActionResult Edit(int Id)
        {
            Partners.Details x = new Partners.Details();
            Partner y = _db.Partner.Where(i => i.PartnerId == Id).SingleOrDefault();
            x.PartnerId = y.PartnerId;
            x.MedicalRecordId = y.MedicalRecordId;
            x.Name = y.Name;
            x.Surname = y.Surname;
            x.BloodType = y.BloodType;
            x.RHFactor = y.RHFactor;
            x.BloodTypes = new List<SelectListItem>
            {
                new SelectListItem(){Value="A", Text="A"},
                new SelectListItem(){Value="B", Text="B"},
                new SelectListItem(){Value="0", Text="0"},
                new SelectListItem(){Value="AB", Text="AB"}
            };
            x.RhFactors = new List<SelectListItem>
            {
                new SelectListItem(){Value="+", Text="+"},
                new SelectListItem(){Value="-", Text="-"}

            };
            return PartialView("_Edit",x);
        }
        [Authorize(Roles = "Doctor, Nurse")]
        public IActionResult SaveExisting(Partners.Details input)
        {
            Partner x = _db.Partner.Where(i => i.PartnerId == input.PartnerId).SingleOrDefault();
            x.Name = input.Name;
            x.Surname = input.Surname;
            x.BloodType = input.BloodType;
            x.RHFactor = input.RHFactor;
            x.MedicalRecordId = input.MedicalRecordId;

            _db.Partner.Update(x);
            _db.SaveChanges();
            _db.Dispose();
            return Redirect("/Records/MedicalRecords/ShowOne?Id=" + input.MedicalRecordId);
        }
        [Authorize(Roles = "Doctor, Nurse")]
        public IActionResult Delete(int Id)
        {
            Partner x = _db.Partner.Where(i => i.PartnerId == Id).SingleOrDefault();
            _db.Partner.Remove(x);
            _db.SaveChanges();
            _db.Dispose();
            return Redirect("/Records/MedicalRecords/ShowOne?Id=" + x.MedicalRecordId);
        }
    }
}

PRENATALv2/Areas/Records/Views/Partners/_Add.cshtml
@using PRENATALv2.Areas.Records.Models
@model Partners.Details

    <div class="container border-bottom">

        <h3><strong class="text-uppercase">Add partner</strong></h3>
        @using (Html.BeginForm("Save", "Partners", FormMethod.Post, new { @class = "form-group" }))
        {
            @Html.AntiForgeryToken();
            <fieldset class="align-content-lg-around">
                @Html.HiddenFor(Model => Model.MedicalRecordId, new { @class = "d-none" })
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.Name, new { @class = "col-sm-12" })<br />
                    @Html.TextBoxFor(Model => Model.Name, new { @class = "form-control" })<br />
                    @Html.ValidationMessageFor(Model => Model.Name, "", new { @class = "text-danger" })
                </div>
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.Surname, new { @class = "col-sm-12" })<br />
                    @Html.TextBoxFor(Model => Model.Surname, new { @class = "form-control" })<br />
                    @Html.ValidationMessageFor(Model => Model.Surname, "", new { @class = "text-danger" })
                </div>
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.BloodType, new { @class = "col-sm-12" })<br />
                    @Html.DropDownListFor(Model => Model.BloodType, new SelectList(Model.BloodTypes, "Value", "Text"), "Select:", new { @class = "form-control", style = "width:120px;" })<br />
                    @Html.ValidationMessageFor(Model => Model.BloodType, "", new { @class = "text-danger" })
                </div>
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.RHFactor, new { @class = "col-sm-12" })<br />
                    @Html.DropDownListFor(Model => Model.RHFactor, new SelectList(Model.RhFactors, "Value", "Text"), "Select:", new { @class = "form-control", style = "width:120px;" })<br />
                    @Html.ValidationMessageFor(Model => Model.RHFactor, "", new { @class = "text-danger" })
                </div>
                <div class="d-inline">
                    <button id="add_cancel" class="btn btn-small form-control">Cancel</button>
                    <input type="submit" class="btn btn-small form-control" value="Save" />
                </div>

            </fieldset>
        }

    </div>
<script>
    $('#add_cancel').click(function () {

        $(this).parent().parent().parent().parent().parent().empty();
    });
</script>

PRENATALv2/Areas/Records/Views/Partners/_Edit.cshtml
@using PRENATALv2.Areas.Records.Models
@model Partners.Details

    <div class="container border-bottom">
        <h3><strong class="text-uppercase">Edit partner</strong></h3>
        @using (Html.BeginForm("SaveExisting", "Partners", FormMethod.Post, new { @class = "form-group" }))
        {
            @Html.AntiForgeryToken();

            <fieldset class="align-content-lg-around">

                @Html.HiddenFor(Model => Model.MedicalRecordId, new { @class = "d-none" })
                @Html.HiddenFor(Model => Model.PartnerId, new { @class = "d-none" })

                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.Name, new { @class = "col-sm-12" })
                    @Html.EditorFor(Model => Model.Name, new { htmlAttributes = new { @class = "form-control" } })<br />
                    @Html.ValidationMessageFor(Model => Model.Name, "", new { @class = "text-danger" })
                </div>
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.Surname, new { @class = "col-sm-12" })
                    @Html.EditorFor(Model => Model.Surname, new { htmlAttributes = new { @class = "form-control" } })<br />
                    @Html.ValidationMessageFor(Model => Model.Surname, "", new { @class = "text-danger" })
                </div>
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.BloodType, new { @class = "col-sm-12" })
                    @Html.DropDownListFor(Model => Model.BloodType, new SelectList(Model.BloodTypes, "Value", "Text", Model.BloodType), "Select:", new { @class = "form-control", style = "width:120px;" })<br />
                    @Html.ValidationMessageFor(Model => Model.BloodType, "", new { @class = "text-danger" })
                </div>
                <div class="d-inline-block">
                    @Html.LabelFor(Model => Model.RHFactor, new { @class = "col-sm-12" })
                    @Html.DropDownListFor(Model => Model.RHFactor, new SelectList(Model.RhFactors, "Value", "Text", Model.RHFactor), "Select:", new { @class = "form-control", style = "width:120px;" })<br />
                    @Html.ValidationMessageFor(Model => Model.RHFactor, "", new { @class = "text-danger" })

                </div>
                <div class="d-inline">
                    <button id="edit_cancel" class="btn btn-small form-control">Cancel</button>
                    <input type="submit" class="btn btn-small form-control" value="Save" />
                </div>
            </fieldset>
        }
    </div>
<script>
    $('#edit_cancel').click(function () {
        $(this).parent().parent().parent().parent().parent().empty();
    });
</script>

PRENATALv2/Areas/Records/Views/Partners/_Show.cshtml
@using PRENATALv2.Areas.Records.Models;
@model Partners
@Html.AntiForgeryToken()
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" />
<div class="container">
    <div class="text-left" style="vertical-align:middle;">
        @if (User.IsInRole("Doctor") || User.IsInRole("Nurse"))
        {
            <button style="vertical-align:middle; font-size:20px;" id="_partner_add" class="btn fas fa-plus-square d-inline"></button>
        }


        <h5 style="vertical-align:middle;" class="d-inline"><strong class="text-uppercase">Partners:</strong></h5>
    </div>

    @{
        if (Model.ListPartners.Count > 0)
        {

            <div class="container">


                <div class="row row_head">
                    <div class="col" hidden>Id</div>
                    <div class="col">Name</div>
                    <div class="col">Surname</div>
                    <div class="col">BloodType</div>
                    <div class="col">RhFactor</div>
                    <div class="col"></div>
                    <div class="col"></div>
                    <div class="col"></div>
                    <div class="col"></div>
                    <div class="col"></div>
                    <div class="col"></div>

                    <div class="col">Actions</div>
                </div>



                @foreach (Partners.Details x in Model.ListPartners)
                {

                    <div class="row row_data">
                        <div class="col" hidden>@x.PartnerId</div>
                        <div class="col">@x.Name</div>
                        <div class="col">@x.Surname</div>
                        <div class="col">@x.BloodType</div>
                        <div class="col">@x.RHFactor</div>
                        <div class="col"></div>
                        <div class="col"></div>
                        <div class="col"></div>
                        <div class="col"></div>
                        <div class="col"></div>
                        <div class="col"></div>

                        <div class="col">
                            @if (User.IsInRole("Doctor") || User.IsInRole("Nurse"))
                            {
                                <i style="font-size:20px;" class="_partner_edit fas fa-edit a_icon"></i>
                                <a style="font-size:20px;" class="_partner_delete fas fa-trash-alt a_icon" href="/Records/Partners/Delete?Id=@x.PartnerId"></a>
                            }
                            else
                            {
                                <div>N/A</div>
                            }

                        </div>
                    </div>


                }

            </div>

        }

    }
    <div class="container" id="_partners_add"></div>
    <div class="container" id="_partners_edit"></div>
</div>


<script>
    $('._partner_edit').click(function () {
        if ($('#_partners_edit').html() == "") {
            var i = $(this).parent().parent().children().html();
            $.ajax({
                url: "/Records/Partners/Edit?Id=" + i,
                type: "POST",
                dataType: "html",
                success: function (data) {
                    $("#_partners_edit").html(data);
                },
                complete: function () {
                    $("form").each(function () { $.data($(this)[0], 'validator', false); });
                    $.validator.unobtrusive.parse("form");
                }
            });
        } else {
            $('#_partners_edit').empty();
        }

    });
    $('#_partner_add').click(function () {
        if ($('#_partners_add').html() == "") {

            $.ajax({
                url: "/Records/Partners/Add?Id="+@Model.MedicalRecordId,
                type: "POST",
                dataType: "html",
                success: function (data) {

                    $("#_partners_add").html(data);

                },
                complete: function () {
                    $("form").each(function () { $.data($(this)[0], 'validator', false); });
                    $.validator.unobtrusive.parse("form");

                }
            });
        } else {
            $('#_partners_add').empty();
        }
    });
</script>