PRENATALv2/Areas/Records/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PRENATALv2.Areas.Home.Data;
using PRENATALv2.Areas.Home.Models;
using PRENATALv2.Areas.Records.Models;
using System.Web;

namespace PRENATALv2.Areas.Records.Controllers
{
    [Area("Records")]
    [Authorize(Roles = "Patient, Doctor, Nurse")]
    [AutoValidateAntiforgeryToken]
    public class PhotosController : Controller
    {
        private Context _db { get; }
        public PhotosController(Context context)
        {
            _db = context;
        }
        public IActionResult Show(int Id)
        {
            PhotosMR x = new PhotosMR();
            x.MedicalRecordId = Id;
            x.Photos = _db.Photos.Where(i => i.MedicalRecordId == Id).Select(y => new PhotosMR.Details
            {
                Date = y.Date,
                Id = y.PhotoId,
                MedicalRecordId = y.MedicalRecordId,
                Title = y.Title,
                Data = y.Data
                
            }).ToList();
            foreach(PhotosMR.Details i in x.Photos)
            {
                i.Base64Data = Convert.ToBase64String(i.Data);
                i.DataURL = string.Format("data:image/jpg;base64,{0}", i.Base64Data);
            }
            return PartialView("_Show", x);
        }
        public IActionResult Add(int Id)
        {
            PhotosMR.Details x = new PhotosMR.Details();
            x.MedicalRecordId = Id;
            return PartialView("_Add",x);
        }
        public IActionResult Save(PhotosMR.Details input)
        {
            foreach (var file in Request.Form.Files)
            {
                Photos img = new Photos();
                img.Title = file.FileName;
                img.MedicalRecordId = input.MedicalRecordId;
                img.Date = DateTime.Now;

                MemoryStream ms = new MemoryStream();
                file.CopyTo(ms);
                img.Data = ms.ToArray();

                ms.Close();
                ms.Dispose();

                _db.Photos.Add(img);
                _db.SaveChanges();
            }
            return Redirect("/Records/MedicalRecords/ShowOne?Id=" + input.MedicalRecordId);

        }
        public IActionResult Delete(int Id)
        {
            Photos x = _db.Photos.Find(Id);
            _db.Photos.Remove(x);
            _db.SaveChanges();
            return Redirect("/Records/MedicalRecords/ShowOne?Id=" + x.MedicalRecordId);
        }

    }
}

PRENATALv2/Areas/Records/Views/Photos/_Add.cshtml
@using PRENATALv2.Areas.Records.Models
@model PhotosMR.Details
<div class="container">
    @using (Html.BeginForm("Save", "Photos", FormMethod.Post, new {@class="form-group", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <fieldset>
            @Html.HiddenFor(Model=>Model.MedicalRecordId)
            <div class="form-group">
                <label class="form-control">Browse:</label>
                
                <input class="form-control" type="file" id="photos" name="photos" multiple="multiple" />
                
            </div>
            <input class="btn btn-prenatal" type="submit" value="Upload Photo(s)" />
        </fieldset>
        
    }

</div>

PRENATALv2/Areas/Records/Views/Photos/_Show.cshtml
@using PRENATALv2.Areas.Records.Models
@model PhotosMR
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" />
@Html.AntiForgeryToken();
<div class="container">
    <div class="text-left" style="vertical-align:middle;">
        @if (User.IsInRole("Doctor") || User.IsInRole("Nurse"))
        {
            <button style="vertical-align:middle; font-size:20px;" id="_add" class="btn fas fa-plus-square d-inline"></button>
        }


        <h5 style="vertical-align:middle;" class="d-inline"><strong class="text-uppercase">Photos:</strong></h5>
    </div>
    @if (Model.Photos.Count() > 0)
    {

        @foreach (PhotosMR.Details x in Model.Photos)
        {
            <div class="d-inline-block text-center" style="border:solid 1px; border-radius:20px; margin:15px; padding:5px;">

                <img class="photos d-block" src="@x.DataURL" />
                <h6 class="d-inline">@x.Title</h6>
                <h6 class="d-inline">@x.Date.ToShortDateString()</h6>
                <div class="d-inline"><a style="font-size:20px;" class="_delete fas fa-trash-alt a_icon" href="/Records/Photos/Delete?Id=@x.Id"></a></div>
            </div>

        }
    }

</div>
<div class="container" id="_adds"></div>
@*<div class="container" id="_edits"></div>*@
<script>

    $('#_add').click(function () {
        if ($('#_adds').html() == "") {

            $.ajax({
                url: "/Records/Photos/Add?Id="+@Model.MedicalRecordId,
                type: "GET",
                dataType: "html",
                success: function (data) {

                    $("#_adds").html(data);

                }

            });
        } else {
            $('#_adds').empty();
        }
    });
</script>