PRENATALv2/Areas/Records/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Reflection.Metadata;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Serialization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PRENATALv2.Areas.Home.Data;
using PRENATALv2.Areas.Home.Models;
using PRENATALv2.Areas.Records.Models;

namespace PRENATALv2.Areas.Records.Controllers
{
    [Area("Records")]
    [Authorize (Roles = "Patient, Doctor, Nurse")]
    [AutoValidateAntiforgeryToken]
    public class FilesController : Controller
    {
        private Context _db { get; }
        private IHostingEnvironment hostingEnv;
        public FilesController(Context context, IHostingEnvironment hostingEnvironment)
        {
            _db = context;
            hostingEnv = hostingEnvironment;
        }
        public IActionResult Show(int Id)
        {
            FilesMR x = new FilesMR();
            x.MedicalRecordId = Id;
            x.Files = _db.Files.Where(i => i.MedicalRecordId == Id).Select(y => new FilesMR.Details
            {
                Id=y.FileId,
                Name=y.Name,
                Date=y.Date,
                Data=y.Data,
                Type=y.Type

            }).ToList();
            return PartialView("_Show", x);
        }
        public IActionResult Add(int Id)
        {
            FilesMR x = new FilesMR();
            x.MedicalRecordId = Id;
            return PartialView("_Add", x);
        }
        public IActionResult Save(FilesMR input, IList<IFormFile> files)
        {
            if (Request.Form.Files != null)
            {
                if (Request.Form.Files.Count() > 0)
                {
                    foreach(IFormFile x in Request.Form.Files)
                    {
                        var fileName = Path.GetFileName(x.FileName);
                        var fileExtension = Path.GetExtension(x.FileName);
                        //var newFileName = String.Concat(Convert.ToString(Guid.NewGuid()), fileExtension);
                        //var newFileName = String.Concat(fileName, fileExtension);
                        var objfiles = new Files()
                        {
                            MedicalRecordId=input.MedicalRecordId,
                            Name = fileName,//newFileName
                            Type = fileExtension,
                            Date = DateTime.Now
                        };
                        using (var target = new MemoryStream())
                        {
                            x.CopyTo(target);
                            objfiles.Data = target.ToArray();
                        }

                        _db.Files.Add(objfiles);
                        _db.SaveChanges();
                    }
                    
                }
            }
            return Redirect("/Records/MedicalRecords/ShowOne?Id=" + input.MedicalRecordId);
        }
        public IActionResult GetFile(int Id)
        {
            Files x = _db.Files.Where(i => i.FileId == Id).SingleOrDefault();

            if (x.Type == ".pdf")
            {                         
                //byte[] pdfBytes = Encoding.ASCII.GetBytes(x.Data.ToString());
                MemoryStream ms = new MemoryStream(x.Data);
                return File(ms, System.Net.Mime.MediaTypeNames.Application.Octet, x.Name);
            }    
            
             return File(x.Data, "application/txt", x.Name);
        }
        public IActionResult Delete(int Id)
        {
            Files x = _db.Files.Find(Id);
            _db.Files.Remove(x);
            _db.SaveChanges();
            return Redirect("/Records/MedicalRecords/ShowOne?Id=" + x.MedicalRecordId);
        }
    }
}

PRENATALv2/Areas/Records/Views/Files/_Add.cshtml
@using PRENATALv2.Areas.Records.Models
@model FilesMR
<div class="container">
    @using (Html.BeginForm("Save", "Files", FormMethod.Post, new {@class="form-group", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <fieldset>
            @Html.HiddenFor(Model=>Model.MedicalRecordId)
            <div class="form-group">
                <label class="form-control">Browse:</label>
                
                <input class="form-control" type="file" id="photos" name="photos" multiple="multiple" />
                
            </div>
            <input class="btn btn-prenatal" type="submit" value="Upload File(s)" />
        </fieldset>
        
    }

</div>

PRENATALv2/Areas/Records/Views/Files/_Show.cshtml
@using PRENATALv2.Areas.Records.Models
@model FilesMR
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" />
@Html.AntiForgeryToken();
<div class="container">
    <div class="text-left" style="vertical-align:middle;">
        @if (User.IsInRole("Doctor") || User.IsInRole("Nurse"))
        {
            <button style="vertical-align:middle; font-size:20px;" id="_add" class="btn fas fa-plus-square d-inline"></button>
        }


        <h5 style="vertical-align:middle;" class="d-inline"><strong class="text-uppercase">Files:</strong></h5>
    </div>
    @if (Model.Files.Count() > 0)
    {
        <div class="row">
            <div hidden class="col">Id</div>
            <div class="col">Name</div>
            <div class="col">Type</div>
            <div class="col">Date</div>
            <div class="col">Actions</div>
        </div>

        @foreach (FilesMR.Details x in Model.Files)
        {
            <div class="row">
                <div hidden class="col">@x.Id</div>
                <div class="col">@x.Name</div>
                <div class="col">@x.Type</div>
                <div class="col">@x.Date</div>
                <div class="col">
                    <a class="_show fas fa-file-alt a_icon" href="/Records/Files/GetFile?Id=@x.Id"></a>
                    <a style="font-size:20px;" class="_delete fas fa-trash-alt a_icon" href="/Records/Files/Delete?Id=@x.Id"></a>
                </div>
            </div>

        }
    }

</div>
<div class="container" id="_shows"></div>
<div class="container" id="_adds"></div>
<script>

    $('#_add').click(function () {
        if ($('#_adds').html() == "") {

            $.ajax({
                url: "/Records/Files/Add?Id="+@Model.MedicalRecordId,
                type: "GET",
                dataType: "html",
                success: function (data) {

                    $("#_adds").html(data);

                }

            });
        } else {
            $('#_adds').empty();
        }
    });

    //$('._show').click(function () {
    //    if ($('#_shows').html() == "") {
            
    //        var i = $(this).parent().parent().children().html();
    //        console.log(i);
    //        $.ajax({
    //            url: "/Records/Files/GetFile?Id=" + i,
    //            type: "GET",
    //            dataType: "html",
    //            success: function (data) {
    //                $("#_shows").html(data);
    //            }
    //        });
    //    } else {
    //        $('#_shows').empty();
    //    }

    //});
</script>